export JULIA_DEPOT_PATH="$BASEDIR/juliaenv/pkg"
export JULIA_PROJECT="$BASEDIR/juliaenv/project"
export JUPYTER_CONFIG_DIR="$BASEDIR/jupyterenv/config"
export JUPYTER_DATA_DIR="$BASEDIR/jupyterenv/data"
export JUPYTER_RUNTIME_DIR="$BASEDIR/jupyterenv/runtime"
