#!/bin/bash
BASEDIR="$(realpath "$(dirname "$0")")"
python3 -m venv "$BASEDIR/ipython-env"
. "$BASEDIR/ipython-env/bin/activate"
pip install jupyter
. "$BASEDIR/environ.sh"
julia "$BASEDIR/install-oscar.jl"
