#!/bin/bash
BASEDIR="$(realpath "$(dirname "$0")")"
. "$BASEDIR/ipython-env/bin/activate"
. "$BASEDIR/environ.sh"
JULIA_KERNEL=$(jupyter kernelspec list | awk '{print $1}' | egrep julia)
jupyter nbconvert \
  --ExecutePreprocessor.kernel_name=$JULIA_KERNEL \
  --to rst \
  --execute "$@"
